emit:
  - "@typespec/openapi3"
  - "@azure-openai/plugin"
options:
  "@typespec/openapi3":
    output-file: "{project-root}/../.openapi3.azure/openapi3-azure-openai-{version}-generated.yaml"
    omit-unreachable-types: true
  "@azure-openai/plugin":
    package-name: "Azure.AI.OpenAI"
    emitter-output-dir: "{project-root}/../.dotnet.azure/sdk/openai/Azure.AI.OpenAI"
    unreferenced-types-handling: keepAll
    new-project: false
    save-inputs: true
