import "./main.tsp";

//import "./audio/client.tsp";
import "./assistants/client.tsp";
//import "./batch/client.tsp";
//import "./chat/client.tsp";
//import "./completions/client.tsp";
//import "./embeddings/client.tsp";
//import "./files/client.tsp";
//import "./fine-tuning/client.tsp";
//import "./images/client.tsp";
//import "./messages/client.tsp";
//import "./models/client.tsp";
//import "./moderations/client.tsp";
//import "./runs/client.tsp";
//import "./threads/client.tsp";
//import "./vector-stores/client.tsp";
