emit:
  - "@typespec/openapi3"
  - "@azure-tools/typespec-csharp"
options:
  "@typespec/openapi3":
    output-file: "{project-root}/../.openapi3/openapi3-openai.yaml"
  "@azure-tools/typespec-csharp":
    emitter-output-dir: "{project-root}/../.dotnet/src"
    unreferenced-types-handling: keepAll
    disable-xml-docs: true
    enable-internal-raw-data: true
    generate-model-factory: false
