emit:
  - "@typespec/openapi3"
  - "@open-ai/plugin"
options:
  "@typespec/openapi3":
    output-file: "{project-root}/../.openapi3/openapi3-openai.yaml"
  "@typespec/http-client-csharp":
    emitter-output-dir: "{project-root}/../.dotnet"
    unreferenced-types-handling: keepAll
    disable-xml-docs: true
    enable-internal-raw-data: true
    save-inputs: true
    generate-model-factory: false
  "@open-ai/plugin":
    emitter-output-dir: "{project-root}/../.dotnet"
    unreferenced-types-handling: keepAll
    disable-xml-docs: true
    enable-internal-raw-data: true
    save-inputs: true
    generate-model-factory: false
