// <auto-generated/>

#nullable disable

namespace Azure.AI.OpenAI.Chat;

[Flags]
public enum DataSourceOutputContextFlags : int
{
    Intent = 1 << 0,
    Citations = 1 << 1,
    AllRetrievedDocuments = 1 << 2,
}