// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using OpenAI;

namespace Azure.AI.OpenAI
{
    /// <summary> The CreateChatCompletionResponseChoice. </summary>
    public partial class AzureCreateChatCompletionResponseChoice : CreateChatCompletionResponseChoice
    {
        public AzureContentFilterResultForChoice ContentFilterResults;
    }
}
