// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace OpenAI.Chat;

internal partial class InternalChatCompletionRequestMessageContentPartImage : ChatMessageContentPart
{
    public InternalChatCompletionRequestMessageContentPartImage(InternalChatCompletionRequestMessageContentPartImageImageUrl imageUrl)
        : this(ChatMessageContentPartKind.Image, serializedAdditionalRawData: null, imageUrl)

    { }

    internal InternalChatCompletionRequestMessageContentPartImage(
        ChatMessageContentPartKind kind,
        IDictionary<string, BinaryData> serializedAdditionalRawData,
        InternalChatCompletionRequestMessageContentPartImageImageUrl imageUrl)
            : base(kind, serializedAdditionalRawData)
    {
        ImageUrl = imageUrl;
        ImageUri = imageUrl?.ImageUri;
        ImageBytes = imageUrl?.ImageBytes;
        ImageBytesMediaType = imageUrl?.ImageBytesMediaType;
        ImageDetailLevel = imageUrl?.Detail;
    }

    internal InternalChatCompletionRequestMessageContentPartImage() : this(null)
    { }
}
