// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace OpenAI.Chat;

internal partial class InternalChatCompletionRequestMessageContentPartText : ChatMessageContentPart
{
    public InternalChatCompletionRequestMessageContentPartText(string text)
        : this(ChatMessageContentPartKind.Text, serializedAdditionalRawData: null, text)
    { }

    internal InternalChatCompletionRequestMessageContentPartText(
        ChatMessageContentPartKind kind,
        IDictionary<string, BinaryData> serializedAdditionalRawData,
        string text)
            : base(kind, serializedAdditionalRawData)
    {
        Text = text;
    }

    internal InternalChatCompletionRequestMessageContentPartText() : this(null)
    { }
}
