namespace OpenAI.Assistants;

public class TextAnnotation
{
    internal readonly MessageContentTextObjectAnnotation _internalAnnotation;
    private readonly MessageContentTextAnnotationsFileCitationObject _fileSearchCitation;
    private readonly MessageContentTextAnnotationsFilePathObject _codeCitation;

    /// <summary>
    /// The index in the message content at which the citation begins.
    /// </summary>
    public virtual int StartIndex => _fileSearchCitation?.StartIndex ?? _codeCitation?.StartIndex ?? -1;

    /// <summary>
    /// The index in the message content at which the citation ends.
    /// </summary>
    public virtual int EndIndex => _fileSearchCitation?.EndIndex ?? _codeCitation?.EndIndex ?? -1;

    /// <summary>
    /// The text in the message content that should be replaced.
    /// </summary>
    public virtual string TextToReplace => _fileSearchCitation?.Text ?? _codeCitation?.Text;
    
    /// <summary>
    /// The ID of the file cited by the <c>file_search</c> tool for this annotation.
    /// </summary>
    public virtual string InputFileId => _fileSearchCitation?.FileCitation?.FileId;

    /// <summary>
    /// The ID of the file that was generated by the <c>code_interpreter</c> tool for this citation.
    /// </summary>
    public virtual string OutputFileId => _codeCitation?.FilePath?.FileId;

    internal TextAnnotation(MessageContentTextObjectAnnotation internalAnnotation)
    {
        _internalAnnotation = internalAnnotation;
        _fileSearchCitation = internalAnnotation as MessageContentTextAnnotationsFileCitationObject;
        _codeCitation = internalAnnotation as MessageContentTextAnnotationsFilePathObject; ;
    }
}