name: Build and Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build: # Test, pack and publish the Open AI nuget package as a build artifact 
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pack
        run: dotnet pack
          -c Release
          -o "${{github.workspace}}/packages"
          ${{ github.ref != 'refs/heads/main' && format('--version-suffix="alpha.{0}"', github.run_number) || '' }}
        working-directory: .dotnet

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: packages/*.nupkg
        if: ${{ github.event_name != 'pull_request' }}
