name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build: # Test, pack and publish the Open AI nuget package as a build artifact 
    runs-on: ubuntu-latest
    env:
      version_suffix_args: ${{ format('--version-suffix="alpha.{0}"', github.run_number) }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: dotnet build
          -c Release
          ${{ env.version_suffix_args }}
        working-directory: .dotnet

      - name: Test
        run: dotnet test
          --no-build
          --configuration Release
          --filter="TestCategory~${{ github.event_name == 'pull_request' && 'Offline' || 'Online' }}|TestCategory~smoke"
          --logger "trx;LogFileName=${{github.workspace}}/artifacts/test-results/full.trx"
        env:
          SECRET_VALUE: ${{ secrets.OPENAI_TOKEN }}
        working-directory: .dotnet

      - name: Run additional code checks
        shell: pwsh
        run: ./Run-Checks.ps1
        working-directory: .scripts

      - name: Pack
        run: dotnet pack
          --no-build
          --configuration Release
          --output "${{github.workspace}}/artifacts/packages"
          ${{ env.version_suffix_args }}
        working-directory: .dotnet

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ${{github.workspace}}/artifacts

      - name: NuGet Autenticate
        if: github.event_name != 'pull_request'
        run: dotnet nuget add source
          "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          --name "github"
          --username ${{ github.actor }}
          --password ${{ secrets.GITHUB_TOKEN }}
          --store-password-in-clear-text
        working-directory: .dotnet

      - name: Publish
        if: github.event_name != 'pull_request'
        run: dotnet nuget push
          ${{github.workspace}}/artifacts/packages/*.nupkg
          --source "github"
          --api-key ${{ secrets.GITHUB_TOKEN }}
          --skip-duplicate
        working-directory: .dotnet

  azure_build: # Build Azure OpenAI for .Net 8.0, .Net 6.0, and .Net Framework 4.6.2
    runs-on: windows-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          # .Net Framework 4.6.2 is pre-installed on Windows 10 versions 1607 and newer
          dotnet-version: |
            8.x
            6.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: dotnet build -p:Configuration=unsigned
        working-directory: .dotnet.azure/sdk/openai

      - name: Publish build artifact
        uses: actions/upload-artifact@v4
        with:
          name: azure_openai_build
          retention-days: 7
          path: |
            .dotnet.azure/artifacts/bin/**/*

      #- name: Test (.net 8.0)
      #  run: dotnet test 
      #    --framework net8.0
      #    --no-build
      #    --filter "(TestCategory!=Live)"
      #    --logger "trx;LogFileName=AzureOpenAITests_net8.0.trx"
      #    --logger:"console;verbosity=normal"
      #    --blame-crash-dump-type full
      #    --blame-hang-dump-type full
      #    --blame-hang-timeout 15minutes
      #    Azure.AI.OpenAI/tests/Azure.AI.OpenAI.Tests.csproj
      #  working-directory: .dotnet.azure/sdk/openai

  azure_test: # Run recorded tests on Azure OpenAI
    needs: azure_build
    strategy:
      matrix:
        os_net:
          - runs-on: ubuntu-latest
            net_install: 8.x
            net: net8.0
          - runs-on: macos-latest
            net_install: 6.x
            net: net6.0
          - runs-on: windows-latest
            # .Net Framework 4.6.2 is pre-installed on Windows 10 versions 1607 and newer
            net: net462
    runs-on: ${{ matrix.os_net.runs-on }}
    steps:
      - name: Setup .NET 6.0 ${{ matrix.os_net.net }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.x
            ${{ matrix.os_net.net_install }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: azure_openai_build
          path: .dotnet.azure/artifacts/bin
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R $GITHUB_WORKSPACE/.dotnet.azure/artifacts
      - name: Test (${{ matrix.os_net.net }})
        run: >-
          dotnet test
          --framework ${{ matrix.os_net.net }}
          --no-build
          --filter "(TestCategory!=Live)"
          --logger "trx;LogFileName=Azure.AI.OpenAI.Tests_${{ matrix.os_net.net }}.trx"
          --logger:"console;verbosity=quiet"
          --blame-crash-dump-type full
          --blame-hang-dump-type full
          --blame-hang-timeout 15minutes
          --results-directory "TestResults"
          Azure.AI.OpenAI/tests/Azure.AI.OpenAI.Tests.csproj
        working-directory: .dotnet.azure/sdk/openai
      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults