name: Validate OpenAPI definition
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test_swagger_editor_validator_service:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Service

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      swagger-editor:
        # Docker Hub image
        image: swaggerapi/swagger-editor
        ports:
          # Maps port 8080 on service container to the host 80
          - 80:8080

    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: openapi.yaml

  # Test, pack and publish the Open AI nuget package as a build artifact 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore
        working-directory: .dotnet

      - name: Build
        run: dotnet build --no-restore
        working-directory: .dotnet

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: .dotnet

      - name: Pack
        run: dotnet pack --no-build -c Release -o out
        working-directory: .dotnet

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: out/*.nupkg
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
