name: Release package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' # SDK Version to use.

      - name: Build
        run: dotnet build
          -c Release
        working-directory: .dotnet

      - name: Test
        run: dotnet test
          --no-build
          --configuration Release
          --filter="TestCategory~Online"
          --logger "trx;LogFileName=${{github.workspace}}/artifacts/test-results/full.trx"
        env:
          SECRET_VALUE: ${{ secrets.OPENAI_TOKEN }}
        working-directory: .dotnet

      - name: Pack
        run: dotnet pack
          --no-build
          --configuration Release
          --output "${{github.workspace}}/artifacts/packages"
        working-directory: .dotnet

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ${{github.workspace}}/artifacts

      - name: NuGet Autenticate
        run: dotnet nuget add source
          "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          --name "github"
          --username ${{ github.actor }}
          --password ${{ secrets.GITHUB_TOKEN }}
          --store-password-in-clear-text
        working-directory: .dotnet

      - name: Publish
        run: dotnet nuget push
          ${{github.workspace}}/artifacts/packages/*.nupkg
          --source "github"
          --api-key ${{ secrets.GITHUB_TOKEN }}
          --skip-duplicate
        working-directory: .dotnet
  
