// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.openai.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.azure.core.util.BinaryData;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The AzureMachineLearningIndexChatDataSourceParameters model.
 */
@Fluent
public final class AzureMachineLearningIndexChatDataSourceParameters
    implements JsonSerializable<AzureMachineLearningIndexChatDataSourceParameters> {
    /*
     * The configured number of documents to feature in the query.
     */
    @Generated
    private Integer topNDocuments;

    /*
     * Whether queries should be restricted to use of the indexed data.
     */
    @Generated
    private Boolean inScope;

    /*
     * The configured strictness of the search relevance filtering.
     * Higher strictness will increase precision but lower recall of the answer.
     */
    @Generated
    private Integer strictness;

    /*
     * Additional instructions for the model to inform how it should behave and any context it should reference when
     * generating a response. You can describe the assistant's personality and tell it how to format responses.
     * This is limited to 100 tokens and counts against the overall token limit.
     */
    @Generated
    private String roleInformation;

    /*
     * The maximum number of rewritten queries that should be sent to the search provider for a single user message.
     * By default, the system will make an automatic determination.
     */
    @Generated
    private Integer maxSearchQueries;

    /*
     * If set to true, the system will allow partial search results to be used and the request will fail if all
     * partial queries fail. If not specified or specified as false, the request will fail if any search query fails.
     */
    @Generated
    private Boolean allowPartialResult;

    /*
     * The output context properties to include on the response.
     * By default, citations and intent will be requested.
     */
    @Generated
    private List<AzureSearchChatDataSourceParametersIncludeContext> includeContexts;

    /*
     * The authentication property.
     */
    @Generated
    private final BinaryData authentication;

    /*
     * The ID of the Azure Machine Learning index project to use.
     */
    @Generated
    private final String projectResourceId;

    /*
     * The name of the Azure Machine Learning index to use.
     */
    @Generated
    private final String name;

    /*
     * The version of the vector index to use.
     */
    @Generated
    private final String version;

    /*
     * A search filter, which is only applicable if the vector index is of the 'AzureSearch' type.
     */
    @Generated
    private String filter;

    /**
     * Creates an instance of AzureMachineLearningIndexChatDataSourceParameters class.
     * 
     * @param authentication the authentication value to set.
     * @param projectResourceId the projectResourceId value to set.
     * @param name the name value to set.
     * @param version the version value to set.
     */
    @Generated
    public AzureMachineLearningIndexChatDataSourceParameters(BinaryData authentication, String projectResourceId,
        String name, String version) {
        this.authentication = authentication;
        this.projectResourceId = projectResourceId;
        this.name = name;
        this.version = version;
    }

    /**
     * Get the topNDocuments property: The configured number of documents to feature in the query.
     * 
     * @return the topNDocuments value.
     */
    @Generated
    public Integer getTopNDocuments() {
        return this.topNDocuments;
    }

    /**
     * Set the topNDocuments property: The configured number of documents to feature in the query.
     * 
     * @param topNDocuments the topNDocuments value to set.
     * @return the AzureMachineLearningIndexChatDataSourceParameters object itself.
     */
    @Generated
    public AzureMachineLearningIndexChatDataSourceParameters setTopNDocuments(Integer topNDocuments) {
        this.topNDocuments = topNDocuments;
        return this;
    }

    /**
     * Get the inScope property: Whether queries should be restricted to use of the indexed data.
     * 
     * @return the inScope value.
     */
    @Generated
    public Boolean isInScope() {
        return this.inScope;
    }

    /**
     * Set the inScope property: Whether queries should be restricted to use of the indexed data.
     * 
     * @param inScope the inScope value to set.
     * @return the AzureMachineLearningIndexChatDataSourceParameters object itself.
     */
    @Generated
    public AzureMachineLearningIndexChatDataSourceParameters setInScope(Boolean inScope) {
        this.inScope = inScope;
        return this;
    }

    /**
     * Get the strictness property: The configured strictness of the search relevance filtering.
     * Higher strictness will increase precision but lower recall of the answer.
     * 
     * @return the strictness value.
     */
    @Generated
    public Integer getStrictness() {
        return this.strictness;
    }

    /**
     * Set the strictness property: The configured strictness of the search relevance filtering.
     * Higher strictness will increase precision but lower recall of the answer.
     * 
     * @param strictness the strictness value to set.
     * @return the AzureMachineLearningIndexChatDataSourceParameters object itself.
     */
    @Generated
    public AzureMachineLearningIndexChatDataSourceParameters setStrictness(Integer strictness) {
        this.strictness = strictness;
        return this;
    }

    /**
     * Get the roleInformation property: Additional instructions for the model to inform how it should behave and any
     * context it should reference when
     * generating a response. You can describe the assistant's personality and tell it how to format responses.
     * This is limited to 100 tokens and counts against the overall token limit.
     * 
     * @return the roleInformation value.
     */
    @Generated
    public String getRoleInformation() {
        return this.roleInformation;
    }

    /**
     * Set the roleInformation property: Additional instructions for the model to inform how it should behave and any
     * context it should reference when
     * generating a response. You can describe the assistant's personality and tell it how to format responses.
     * This is limited to 100 tokens and counts against the overall token limit.
     * 
     * @param roleInformation the roleInformation value to set.
     * @return the AzureMachineLearningIndexChatDataSourceParameters object itself.
     */
    @Generated
    public AzureMachineLearningIndexChatDataSourceParameters setRoleInformation(String roleInformation) {
        this.roleInformation = roleInformation;
        return this;
    }

    /**
     * Get the maxSearchQueries property: The maximum number of rewritten queries that should be sent to the search
     * provider for a single user message.
     * By default, the system will make an automatic determination.
     * 
     * @return the maxSearchQueries value.
     */
    @Generated
    public Integer getMaxSearchQueries() {
        return this.maxSearchQueries;
    }

    /**
     * Set the maxSearchQueries property: The maximum number of rewritten queries that should be sent to the search
     * provider for a single user message.
     * By default, the system will make an automatic determination.
     * 
     * @param maxSearchQueries the maxSearchQueries value to set.
     * @return the AzureMachineLearningIndexChatDataSourceParameters object itself.
     */
    @Generated
    public AzureMachineLearningIndexChatDataSourceParameters setMaxSearchQueries(Integer maxSearchQueries) {
        this.maxSearchQueries = maxSearchQueries;
        return this;
    }

    /**
     * Get the allowPartialResult property: If set to true, the system will allow partial search results to be used and
     * the request will fail if all
     * partial queries fail. If not specified or specified as false, the request will fail if any search query fails.
     * 
     * @return the allowPartialResult value.
     */
    @Generated
    public Boolean isAllowPartialResult() {
        return this.allowPartialResult;
    }

    /**
     * Set the allowPartialResult property: If set to true, the system will allow partial search results to be used and
     * the request will fail if all
     * partial queries fail. If not specified or specified as false, the request will fail if any search query fails.
     * 
     * @param allowPartialResult the allowPartialResult value to set.
     * @return the AzureMachineLearningIndexChatDataSourceParameters object itself.
     */
    @Generated
    public AzureMachineLearningIndexChatDataSourceParameters setAllowPartialResult(Boolean allowPartialResult) {
        this.allowPartialResult = allowPartialResult;
        return this;
    }

    /**
     * Get the includeContexts property: The output context properties to include on the response.
     * By default, citations and intent will be requested.
     * 
     * @return the includeContexts value.
     */
    @Generated
    public List<AzureSearchChatDataSourceParametersIncludeContext> getIncludeContexts() {
        return this.includeContexts;
    }

    /**
     * Set the includeContexts property: The output context properties to include on the response.
     * By default, citations and intent will be requested.
     * 
     * @param includeContexts the includeContexts value to set.
     * @return the AzureMachineLearningIndexChatDataSourceParameters object itself.
     */
    @Generated
    public AzureMachineLearningIndexChatDataSourceParameters
        setIncludeContexts(List<AzureSearchChatDataSourceParametersIncludeContext> includeContexts) {
        this.includeContexts = includeContexts;
        return this;
    }

    /**
     * Get the authentication property: The authentication property.
     * 
     * @return the authentication value.
     */
    @Generated
    public BinaryData getAuthentication() {
        return this.authentication;
    }

    /**
     * Get the projectResourceId property: The ID of the Azure Machine Learning index project to use.
     * 
     * @return the projectResourceId value.
     */
    @Generated
    public String getProjectResourceId() {
        return this.projectResourceId;
    }

    /**
     * Get the name property: The name of the Azure Machine Learning index to use.
     * 
     * @return the name value.
     */
    @Generated
    public String getName() {
        return this.name;
    }

    /**
     * Get the version property: The version of the vector index to use.
     * 
     * @return the version value.
     */
    @Generated
    public String getVersion() {
        return this.version;
    }

    /**
     * Get the filter property: A search filter, which is only applicable if the vector index is of the 'AzureSearch'
     * type.
     * 
     * @return the filter value.
     */
    @Generated
    public String getFilter() {
        return this.filter;
    }

    /**
     * Set the filter property: A search filter, which is only applicable if the vector index is of the 'AzureSearch'
     * type.
     * 
     * @param filter the filter value to set.
     * @return the AzureMachineLearningIndexChatDataSourceParameters object itself.
     */
    @Generated
    public AzureMachineLearningIndexChatDataSourceParameters setFilter(String filter) {
        this.filter = filter;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeUntypedField("authentication", this.authentication.toObject(Object.class));
        jsonWriter.writeStringField("project_resource_id", this.projectResourceId);
        jsonWriter.writeStringField("name", this.name);
        jsonWriter.writeStringField("version", this.version);
        jsonWriter.writeNumberField("top_n_documents", this.topNDocuments);
        jsonWriter.writeBooleanField("in_scope", this.inScope);
        jsonWriter.writeNumberField("strictness", this.strictness);
        jsonWriter.writeStringField("role_information", this.roleInformation);
        jsonWriter.writeNumberField("max_search_queries", this.maxSearchQueries);
        jsonWriter.writeBooleanField("allow_partial_result", this.allowPartialResult);
        jsonWriter.writeArrayField("include_contexts", this.includeContexts,
            (writer, element) -> writer.writeString(element == null ? null : element.toString()));
        jsonWriter.writeStringField("filter", this.filter);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of AzureMachineLearningIndexChatDataSourceParameters from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of AzureMachineLearningIndexChatDataSourceParameters if the JsonReader was pointing to an
     * instance of it, or null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the AzureMachineLearningIndexChatDataSourceParameters.
     */
    @Generated
    public static AzureMachineLearningIndexChatDataSourceParameters fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            BinaryData authentication = null;
            String projectResourceId = null;
            String name = null;
            String version = null;
            Integer topNDocuments = null;
            Boolean inScope = null;
            Integer strictness = null;
            String roleInformation = null;
            Integer maxSearchQueries = null;
            Boolean allowPartialResult = null;
            List<AzureSearchChatDataSourceParametersIncludeContext> includeContexts = null;
            String filter = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("authentication".equals(fieldName)) {
                    authentication
                        = reader.getNullable(nonNullReader -> BinaryData.fromObject(nonNullReader.readUntyped()));
                } else if ("project_resource_id".equals(fieldName)) {
                    projectResourceId = reader.getString();
                } else if ("name".equals(fieldName)) {
                    name = reader.getString();
                } else if ("version".equals(fieldName)) {
                    version = reader.getString();
                } else if ("top_n_documents".equals(fieldName)) {
                    topNDocuments = reader.getNullable(JsonReader::getInt);
                } else if ("in_scope".equals(fieldName)) {
                    inScope = reader.getNullable(JsonReader::getBoolean);
                } else if ("strictness".equals(fieldName)) {
                    strictness = reader.getNullable(JsonReader::getInt);
                } else if ("role_information".equals(fieldName)) {
                    roleInformation = reader.getString();
                } else if ("max_search_queries".equals(fieldName)) {
                    maxSearchQueries = reader.getNullable(JsonReader::getInt);
                } else if ("allow_partial_result".equals(fieldName)) {
                    allowPartialResult = reader.getNullable(JsonReader::getBoolean);
                } else if ("include_contexts".equals(fieldName)) {
                    includeContexts = reader.readArray(
                        reader1 -> AzureSearchChatDataSourceParametersIncludeContext.fromString(reader1.getString()));
                } else if ("filter".equals(fieldName)) {
                    filter = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            AzureMachineLearningIndexChatDataSourceParameters deserializedAzureMachineLearningIndexChatDataSourceParameters
                = new AzureMachineLearningIndexChatDataSourceParameters(authentication, projectResourceId, name,
                    version);
            deserializedAzureMachineLearningIndexChatDataSourceParameters.topNDocuments = topNDocuments;
            deserializedAzureMachineLearningIndexChatDataSourceParameters.inScope = inScope;
            deserializedAzureMachineLearningIndexChatDataSourceParameters.strictness = strictness;
            deserializedAzureMachineLearningIndexChatDataSourceParameters.roleInformation = roleInformation;
            deserializedAzureMachineLearningIndexChatDataSourceParameters.maxSearchQueries = maxSearchQueries;
            deserializedAzureMachineLearningIndexChatDataSourceParameters.allowPartialResult = allowPartialResult;
            deserializedAzureMachineLearningIndexChatDataSourceParameters.includeContexts = includeContexts;
            deserializedAzureMachineLearningIndexChatDataSourceParameters.filter = filter;

            return deserializedAzureMachineLearningIndexChatDataSourceParameters;
        });
    }
}
