// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.openai.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * Represents a data source configuration that will use an Azure Machine Learning vector index.
 */
@Immutable
public final class AzureMachineLearningIndexChatDataSource extends AzureChatDataSource {
    /*
     * The differentiating type identifier for the data source.
     */
    @Generated
    private String type = "azure_ml_index";

    /*
     * The parameter information to control the use of the Azure Machine Learning Index data source.
     */
    @Generated
    private final AzureMachineLearningIndexChatDataSourceParameters parameters;

    /**
     * Creates an instance of AzureMachineLearningIndexChatDataSource class.
     * 
     * @param parameters the parameters value to set.
     */
    @Generated
    public AzureMachineLearningIndexChatDataSource(AzureMachineLearningIndexChatDataSourceParameters parameters) {
        this.parameters = parameters;
    }

    /**
     * Get the type property: The differentiating type identifier for the data source.
     * 
     * @return the type value.
     */
    @Generated
    @Override
    public String getType() {
        return this.type;
    }

    /**
     * Get the parameters property: The parameter information to control the use of the Azure Machine Learning Index
     * data source.
     * 
     * @return the parameters value.
     */
    @Generated
    public AzureMachineLearningIndexChatDataSourceParameters getParameters() {
        return this.parameters;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeJsonField("parameters", this.parameters);
        jsonWriter.writeStringField("type", this.type);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of AzureMachineLearningIndexChatDataSource from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of AzureMachineLearningIndexChatDataSource if the JsonReader was pointing to an instance of
     * it, or null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the AzureMachineLearningIndexChatDataSource.
     */
    @Generated
    public static AzureMachineLearningIndexChatDataSource fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            AzureMachineLearningIndexChatDataSourceParameters parameters = null;
            String type = "azure_ml_index";
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("parameters".equals(fieldName)) {
                    parameters = AzureMachineLearningIndexChatDataSourceParameters.fromJson(reader);
                } else if ("type".equals(fieldName)) {
                    type = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            AzureMachineLearningIndexChatDataSource deserializedAzureMachineLearningIndexChatDataSource
                = new AzureMachineLearningIndexChatDataSource(parameters);
            deserializedAzureMachineLearningIndexChatDataSource.type = type;

            return deserializedAzureMachineLearningIndexChatDataSource;
        });
    }
}
